pygments: true
permalink: /:categories/:title/
email: scottwater@gmail.com
baseUrl: http://scottw.com
author: Scott Watermasysk
title: Scott Watermasysk
feedurl: http://feeds.simpable.com/simpable
exclude: [lib, config.ru, Rakefile]
